<?php

namespace AppBundle\Repository;

/**
 * Objects_treeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Objects_treeRepository extends \Doctrine\ORM\EntityRepository
{
}
