<?php

namespace AppBundle\Repository;

/**
 * Objects_infosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Objects_infosRepository extends \Doctrine\ORM\EntityRepository
{
}
