<?php

namespace AppBundle\Repository;

/**
 * Objects_infos_resourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Objects_infos_resourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
