<?php

namespace AppBundle\Repository;

/**
 * Object_infos_resources_typesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Object_infos_resources_typesRepository extends \Doctrine\ORM\EntityRepository
{
}
