<?php

namespace AppBundle\Repository;

/**
 * UnityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnityTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
