<?php

namespace AppBundle\Repository;

/**
 * HumansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersTreeRepository extends \Doctrine\ORM\EntityRepository
{
}
